version: '2.4'
services:
  vsg-postgres:
    image: postgres:14-alpine
    command: ["postgres"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=diagraph
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - vsg-network

  vsg-mailhog:
    image: mailhog/mailhog
    command: ["mailhog"]
    ports:
      - "1025:1025"
      - "8025:8025"
    expose:
      - "1025"
    networks:
      - vsg-network

networks:
  vsg-network:
    name: vsg-network
